linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - dogsled
    - errcheck
    - exportloopref
    - gci
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - misspell
    - nakedret
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - staticcheck
    - stylecheck
    - thelper
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
disable:
  - depguard # Disabling because it is causing CI to break. See issue https://github.com/golangci/golangci-lint/issues/3906 fore more
run:
  skip-files:
    - "kubernetes/.*"
  timeout: 5m
issue:
  max-same-issues: 0
  max-per-linter: 0
issues:
  exclude-rules:
    - path: "pkg/testcases/*"
      linters:
        - gosec
      text: "G204:"
